import SwiftUI

/// The licences of the open-source code in the app: Microsoft's outlook-pst
/// crate and the other Rust crates of the core (generated by
/// `scripts/generate-licenses.py`).
struct LicensesView: View {
    @State private var licenses: ThirdPartyLicenses?
    @State private var filter = ""

    var body: some View {
        List {
            Section {
                Text("PST Viewer reads Outlook data files with Microsoft’s outlook-pst library and uses the following open-source components. Thank you to their authors.")
                    .font(.subheadline)
                    .foregroundStyle(.secondary)
            }
            if let licenses {
                Section {
                    ForEach(licenses.crates.filter(matches)) { crate in
                        NavigationLink {
                            LicenseTextView(crate: crate, texts: crate.texts.compactMap { licenses.texts[$0] })
                        } label: {
                            VStack(alignment: .leading, spacing: 2) {
                                HStack(alignment: .firstTextBaseline) {
                                    Text(verbatim: crate.name).font(.body.weight(.medium))
                                    Text(verbatim: crate.version).font(.caption).foregroundStyle(.secondary)
                                }
                                Text(verbatim: crate.license)
                                    .font(.caption)
                                    .foregroundStyle(.secondary)
                            }
                        }
                    }
                }
            }
        }
        .searchable(text: $filter)
        .navigationTitle("Open-Source Licences")
        .navigationBarTitleDisplayMode(.inline)
        .task {
            licenses = ThirdPartyLicenses.load()
        }
    }

    private func matches(_ crate: ThirdPartyLicenses.Crate) -> Bool {
        filter.isEmpty || crate.name.localizedCaseInsensitiveContains(filter) || crate.license.localizedCaseInsensitiveContains(filter)
    }
}

private struct LicenseTextView: View {
    let crate: ThirdPartyLicenses.Crate
    let texts: [String]

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                VStack(alignment: .leading, spacing: 4) {
                    Text(verbatim: "\(crate.name) \(crate.version)").font(.headline)
                    Text(verbatim: crate.license).foregroundStyle(.secondary)
                    if let url = URL(string: crate.repository), !crate.repository.isEmpty {
                        Link(crate.repository, destination: url)
                            .font(.footnote)
                    }
                }
                ForEach(texts, id: \.self) { text in
                    Text(verbatim: text)
                        .font(.caption.monospaced())
                        .textSelection(.enabled)
                        .padding(12)
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .background(Color(.secondarySystemBackground), in: .rect(cornerRadius: 10, style: .continuous))
                }
            }
            .padding(20)
        }
        .navigationTitle(Text(verbatim: crate.name))
        .navigationBarTitleDisplayMode(.inline)
    }
}

/// The bundled `ThirdPartyLicenses.json`.
struct ThirdPartyLicenses: Decodable {
    struct Crate: Decodable, Identifiable {
        let name: String
        let version: String
        let license: String
        let repository: String
        let texts: [String]

        var id: String { "\(name)@\(version)" }
    }

    let crates: [Crate]
    let texts: [String: String]

    static func load() -> ThirdPartyLicenses? {
        guard let url = Bundle.main.url(forResource: "ThirdPartyLicenses", withExtension: "json"),
              let data = try? Data(contentsOf: url) else { return nil }
        return try? JSONDecoder().decode(ThirdPartyLicenses.self, from: data)
    }
}
