import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
}

// Release signing: environment variables (CI) or an untracked keystore.properties
// next to this project's settings file. Without them, release builds are signed
// with the debug key so that they can be installed locally.
val keystoreProperties = Properties().apply {
    val file = rootProject.file("keystore.properties")
    if (file.isFile) file.inputStream().use(::load)
}

fun signingValue(property: String, variable: String): String? =
    providers.environmentVariable(variable).orNull ?: keystoreProperties.getProperty(property)

val releaseStoreFile = signingValue("storeFile", "PST_VIEWER_KEYSTORE")

android {
    namespace = "de.kernich.pstviewer"
    compileSdk = 37

    defaultConfig {
        applicationId = "de.kernich.pstviewer"
        minSdk = 26
        targetSdk = 37
        versionCode = 1
        versionName = "1.0.0"
        // The ABIs the Rust core is built for (crates/core/scripts/build-android.sh);
        // JNA ships more, which would install on devices the core cannot run on.
        ndk { abiFilters += listOf("arm64-v8a", "armeabi-v7a", "x86_64") }
    }

    signingConfigs {
        if (releaseStoreFile != null) {
            create("release") {
                storeFile = rootProject.file(releaseStoreFile)
                storePassword = signingValue("storePassword", "PST_VIEWER_KEYSTORE_PASSWORD")
                keyAlias = signingValue("keyAlias", "PST_VIEWER_KEY_ALIAS")
                keyPassword = signingValue("keyPassword", "PST_VIEWER_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            signingConfig = signingConfigs.findByName("release") ?: signingConfigs.getByName("debug")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    androidResources {
        generateLocaleConfig = true
    }

    sourceSets {
        // Kotlin bindings of the Rust core, generated by crates/core/scripts/build-android.sh.
        getByName("main").kotlin.directories.add("src/generated/kotlin")
    }

    lint {
        lintConfig = file("lint.xml")
        abortOnError = true
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

// Builds the Rust core (crates/core) into src/main/jniLibs and generates its Kotlin
// bindings. Skip it with -PskipRustCore=true when the outputs are already in place;
// -PrustProfile=dev builds an unoptimised core faster.
val repoRoot = rootDir.resolve("../..").canonicalFile
val buildRustCore = tasks.register<Exec>("buildRustCore") {
    description = "Builds the Rust core for Android and generates the Kotlin bindings."
    group = "build"
    val profile = providers.gradleProperty("rustProfile").orElse("release")
    val skip = providers.gradleProperty("skipRustCore").map(String::toBoolean).orElse(false)
    onlyIf { !skip.get() }
    workingDir = repoRoot
    commandLine("sh", "crates/core/scripts/build-android.sh")
    environment("PROFILE", profile.get())
    inputs.property("profile", profile)
    inputs.files(
        repoRoot.resolve("Cargo.toml"),
        repoRoot.resolve("Cargo.lock"),
        repoRoot.resolve("crates/core/Cargo.toml"),
        repoRoot.resolve("crates/core/uniffi.toml"),
        repoRoot.resolve("crates/core/scripts/build-android.sh"),
    )
    inputs.dir(repoRoot.resolve("crates/core/src"))
    inputs.dir(repoRoot.resolve("crates/vendor"))
    inputs.dir(repoRoot.resolve("crates/uniffi-bindgen"))
    outputs.dir(layout.projectDirectory.dir("src/main/jniLibs"))
    outputs.dir(layout.projectDirectory.dir("src/generated/kotlin"))
}

tasks.named("preBuild") { dependsOn(buildRustCore) }

dependencies {
    implementation(platform(libs.compose.bom))
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.lifecycle.viewmodel.navigation3)
    implementation(libs.androidx.navigation3.runtime)
    implementation(libs.androidx.navigation3.ui)
    implementation(libs.compose.foundation)
    implementation(libs.compose.material3)
    implementation(libs.compose.material3.adaptive)
    implementation(libs.compose.material3.adaptive.layout)
    implementation(libs.compose.material3.adaptive.navigation)
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.jna) { artifact { type = "aar" } }
    debugImplementation(libs.compose.ui.tooling)
    testImplementation(libs.junit)
}
