package de.kernich.pstviewer.ui.settings

import android.content.res.Resources
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.WindowInsets
import androidx.compose.foundation.layout.WindowInsetsSides
import androidx.compose.foundation.layout.asPaddingValues
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.navigationBarsPadding
import androidx.compose.foundation.layout.only
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.safeDrawing
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyListScope
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.text.selection.SelectionContainer
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.LargeTopAppBar
import androidx.compose.material3.ListItem
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBarDefaults
import androidx.compose.material3.rememberModalBottomSheetState
import androidx.compose.material3.rememberTopAppBarState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.produceState
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.input.nestedscroll.nestedScroll
import androidx.compose.ui.platform.LocalResources
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.semantics.heading
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import de.kernich.pstviewer.R
import de.kernich.pstviewer.ui.components.ActionIcon
import de.kernich.pstviewer.ui.components.readableWidth
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONObject

/** A component with its licence and the full licence text. */
private class License(val name: String, val detail: String, val text: String)

private const val APACHE = "Apache-2.0"

/** Rust crates of the core (generated by scripts/generate-rust-licenses.py) and the app's libraries. */
private fun loadLicenses(resources: Resources): Pair<List<License>, List<License>> {
    val json = JSONObject(resources.openRawResource(R.raw.rust_licenses).bufferedReader().use { it.readText() })
    val texts = json.getJSONArray("texts").let { array -> List(array.length()) { array.getString(it) } }
    val apache = texts.first { it.startsWith("Apache License") }
    val crates = json.getJSONArray("crates").let { array ->
        List(array.length()) { index ->
            val crate = array.getJSONObject(index)
            val indices = crate.getJSONArray("texts")
            val license = crate.getString("license")
            License(
                name = "${crate.getString("name")} ${crate.getString("version")}",
                // The PST parser the app is built on (github.com/microsoft/outlook-pst-rs).
                detail = if (crate.getString("name") == "outlook-pst") "$license · Microsoft Corporation" else license,
                text = List(indices.length()) { texts[indices.getInt(it)] }.joinToString("\n\n"),
            )
        }
    }.sortedByDescending { it.name.startsWith("outlook-pst ") }
    val usedUnder = resources.getString(R.string.licenses_used_under, APACHE)
    val app = listOf(
        License("Jetpack Compose, AndroidX", "$APACHE · Google", apache),
        License("Material Symbols", "$APACHE · Google", apache),
        License("Kotlin, kotlinx.coroutines", "$APACHE · JetBrains", apache),
        License("JNA (Java Native Access)", "$APACHE OR LGPL-2.1-or-later · $usedUnder", apache),
    )
    return app to crates
}

/** Open-source licences of the app and the Rust core. */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun LicensesScreen(onBack: () -> Unit) {
    val resources = LocalResources.current
    val licenses by produceState<Pair<List<License>, List<License>>?>(null, resources) {
        value = withContext(Dispatchers.IO) { loadLicenses(resources) }
    }
    var shown by remember { mutableStateOf<License?>(null) }
    val scrollBehavior = TopAppBarDefaults.exitUntilCollapsedScrollBehavior(rememberTopAppBarState())
    Scaffold(
        modifier = Modifier.readableWidth().nestedScroll(scrollBehavior.nestedScrollConnection),
        topBar = {
            LargeTopAppBar(
                title = { Text(stringResource(R.string.licenses)) },
                navigationIcon = { ActionIcon(R.drawable.ic_arrow_back, stringResource(R.string.back), onBack) },
                scrollBehavior = scrollBehavior,
            )
        },
        contentWindowInsets = WindowInsets(0),
    ) { padding ->
        val current = licenses
        if (current == null) {
            Box(Modifier.padding(padding).fillMaxSize(), contentAlignment = Alignment.Center) { CircularProgressIndicator() }
        } else {
            LazyColumn(
                modifier = Modifier.padding(padding).fillMaxSize(),
                contentPadding = WindowInsets.safeDrawing.only(WindowInsetsSides.Bottom + WindowInsetsSides.Horizontal).asPaddingValues(),
            ) {
                licenseSection(R.string.licenses_app, current.first) { shown = it }
                licenseSection(R.string.licenses_core, current.second) { shown = it }
            }
        }
    }
    shown?.let { license ->
        ModalBottomSheet(onDismissRequest = { shown = null }, sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)) {
            Column(Modifier.fillMaxWidth().navigationBarsPadding().padding(horizontal = 20.dp)) {
                Text(license.name, style = MaterialTheme.typography.titleLarge, modifier = Modifier.semantics { heading() })
                Text(license.detail, style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.onSurfaceVariant)
                SelectionContainer(Modifier.padding(vertical = 12.dp).verticalScroll(rememberScrollState())) {
                    Text(license.text, style = MaterialTheme.typography.bodySmall, fontFamily = FontFamily.Monospace)
                }
            }
        }
    }
}

private fun LazyListScope.licenseSection(title: Int, licenses: List<License>, onShow: (License) -> Unit) {
    item(key = title) {
        Text(
            stringResource(title),
            style = MaterialTheme.typography.titleSmall,
            color = MaterialTheme.colorScheme.primary,
            modifier = Modifier.padding(start = 16.dp, end = 16.dp, top = 24.dp, bottom = 8.dp).semantics { heading() },
        )
    }
    items(licenses, key = { "$title/${it.name}" }) { license ->
        ListItem(
            headlineContent = { Text(license.name) },
            supportingContent = { Text(license.detail) },
            modifier = Modifier.clickable { onShow(license) },
        )
    }
}
