package de.kernich.pstviewer.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Fallback colour schemes when dynamic colour is unavailable or turned off:
 * the Material "vibrant" scheme generated from the brand colour #4A5CFF
 * (material-color-utilities).
 */
val BrandLightColors = lightColorScheme(
    primary = Color(0xFF293FFF),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFDFE0FF),
    onPrimaryContainer = Color(0xFF001FDE),
    inversePrimary = Color(0xFFBDC2FF),
    secondary = Color(0xFF615A7C),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE7DEFF),
    onSecondaryContainer = Color(0xFF494263),
    tertiary = Color(0xFF6D5484),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFF0DBFF),
    onTertiaryContainer = Color(0xFF543C6B),
    background = Color(0xFFFBF8FF),
    onBackground = Color(0xFF1A1B25),
    surface = Color(0xFFFBF8FF),
    onSurface = Color(0xFF1A1B25),
    surfaceVariant = Color(0xFFE2E1F3),
    onSurfaceVariant = Color(0xFF454654),
    surfaceTint = Color(0xFF293FFF),
    inverseSurface = Color(0xFF2F303A),
    inverseOnSurface = Color(0xFFF1EFFE),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    outline = Color(0xFF767685),
    outlineVariant = Color(0xFFC6C5D6),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFBF8FF),
    surfaceContainer = Color(0xFFEEECFB),
    surfaceContainerHigh = Color(0xFFE8E7F5),
    surfaceContainerHighest = Color(0xFFE3E1EF),
    surfaceContainerLow = Color(0xFFF4F2FF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceDim = Color(0xFFDAD8E7),
    primaryFixed = Color(0xFFDFE0FF),
    primaryFixedDim = Color(0xFFBDC2FF),
    onPrimaryFixed = Color(0xFF000865),
    onPrimaryFixedVariant = Color(0xFF001FDE),
    secondaryFixed = Color(0xFFE7DEFF),
    secondaryFixedDim = Color(0xFFCBC1E9),
    onSecondaryFixed = Color(0xFF1D1735),
    onSecondaryFixedVariant = Color(0xFF494263),
    tertiaryFixed = Color(0xFFF0DBFF),
    tertiaryFixedDim = Color(0xFFD9BBF2),
    onTertiaryFixed = Color(0xFF27103C),
    onTertiaryFixedVariant = Color(0xFF543C6B),
)

val BrandDarkColors = darkColorScheme(
    primary = Color(0xFFBDC2FF),
    onPrimary = Color(0xFF00139F),
    primaryContainer = Color(0xFF001FDE),
    onPrimaryContainer = Color(0xFFDFE0FF),
    inversePrimary = Color(0xFF293FFF),
    secondary = Color(0xFFCBC1E9),
    onSecondary = Color(0xFF332C4C),
    secondaryContainer = Color(0xFF494263),
    onSecondaryContainer = Color(0xFFE7DEFF),
    tertiary = Color(0xFFD9BBF2),
    onTertiary = Color(0xFF3D2653),
    tertiaryContainer = Color(0xFF543C6B),
    onTertiaryContainer = Color(0xFFF0DBFF),
    background = Color(0xFF12131C),
    onBackground = Color(0xFFE3E1EF),
    surface = Color(0xFF12131C),
    onSurface = Color(0xFFE3E1EF),
    surfaceVariant = Color(0xFF454654),
    onSurfaceVariant = Color(0xFFC6C5D6),
    surfaceTint = Color(0xFFBDC2FF),
    inverseSurface = Color(0xFFE3E1EF),
    inverseOnSurface = Color(0xFF2F303A),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF8F8F9F),
    outlineVariant = Color(0xFF454654),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF383843),
    surfaceContainer = Color(0xFF1E1F29),
    surfaceContainerHigh = Color(0xFF292934),
    surfaceContainerHighest = Color(0xFF33343F),
    surfaceContainerLow = Color(0xFF1A1B25),
    surfaceContainerLowest = Color(0xFF0D0D17),
    surfaceDim = Color(0xFF12131C),
    primaryFixed = Color(0xFFDFE0FF),
    primaryFixedDim = Color(0xFFBDC2FF),
    onPrimaryFixed = Color(0xFF000865),
    onPrimaryFixedVariant = Color(0xFF001FDE),
    secondaryFixed = Color(0xFFE7DEFF),
    secondaryFixedDim = Color(0xFFCBC1E9),
    onSecondaryFixed = Color(0xFF1D1735),
    onSecondaryFixedVariant = Color(0xFF494263),
    tertiaryFixed = Color(0xFFF0DBFF),
    tertiaryFixedDim = Color(0xFFD9BBF2),
    onTertiaryFixed = Color(0xFF27103C),
    onTertiaryFixedVariant = Color(0xFF543C6B),
)
