import type { Metadata } from 'next'
import { locales, ogLocales, type Locale } from './i18n'
import { ogImage, ogImagePath } from './og'
import { alternatePaths, pathFor, type Route } from './routes'
import { siteConfig } from './site'

interface PageMetadataOptions {
  locale: Locale
  route: Route
  title: string
  description: string
  /** Use `title` as is instead of the `%s · PST Viewer` template. */
  absoluteTitle?: boolean
}

/**
 * Per-page metadata with canonical URL, hreflang alternates, Open Graph and
 * Twitter card. URLs are relative and resolved against `metadataBase`
 * (set in the locale layout). The Open Graph image is generated by
 * `app/[locale]/opengraph-image.tsx`.
 */
export function pageMetadata({ locale, route, title, description, absoluteTitle = false }: PageMetadataOptions): Metadata {
  const path = pathFor(locale, route)
  const fullTitle = absoluteTitle ? title : `${title} · ${siteConfig.name}`
  // Nested pages replace the parent's `openGraph` object, so the image is referenced explicitly.
  const images = [{ url: ogImagePath(locale), ...ogImage.size, alt: ogImage.alt, type: ogImage.contentType }]

  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: {
      canonical: path,
      languages: alternatePaths(route),
    },
    openGraph: {
      type: 'website',
      siteName: siteConfig.name,
      title: fullTitle,
      description,
      url: path,
      locale: ogLocales[locale],
      alternateLocale: locales.filter((l) => l !== locale).map((l) => ogLocales[l]),
      images,
    },
    twitter: {
      card: 'summary_large_image',
      title: fullTitle,
      description,
      images,
    },
  }
}
