import type { Metadata } from 'next'
import { locales, ogLocales, type Locale } from './i18n'
import { appleTouchIconPath, ogImage, ogImagePath } from './og'
import { alternatePaths, pathFor, type Route } from './routes'
import { absoluteUrl, siteConfig } from './site'

/**
 * Favicon (`app/icon.svg`) and Apple touch icon with absolute URLs. Set on
 * every document; an explicit `icons` field replaces the file-based icon tags.
 */
export const siteIcons: Metadata['icons'] = {
  icon: [{ url: absoluteUrl('/icon.svg'), type: 'image/svg+xml' }],
  apple: absoluteUrl(appleTouchIconPath),
}

interface PageMetadataOptions {
  locale: Locale
  route: Route
  title: string
  description: string
  /** Use `title` as is instead of the `%s · PST Viewer` template. */
  absoluteTitle?: boolean
}

/**
 * Per-page metadata with canonical URL, hreflang alternates, Open Graph and
 * Twitter card. All URLs are absolute and built from `NEXT_PUBLIC_SITE_URL`,
 * which already contains the base path (resolving root-relative URLs against
 * a `metadataBase` with a path would drop it). The Open Graph image is
 * generated by `app/[locale]/og-image.png/route.tsx`.
 */
export function pageMetadata({ locale, route, title, description, absoluteTitle = false }: PageMetadataOptions): Metadata {
  const url = absoluteUrl(pathFor(locale, route))
  const fullTitle = absoluteTitle ? title : `${title} · ${siteConfig.name}`
  // Nested pages replace the parent's `openGraph` object, so the image is referenced explicitly.
  const images = [{ url: absoluteUrl(ogImagePath(locale)), ...ogImage.size, alt: ogImage.alt, type: ogImage.contentType }]

  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: {
      canonical: url,
      languages: Object.fromEntries(Object.entries(alternatePaths(route)).map(([lang, path]) => [lang, absoluteUrl(path)])),
    },
    openGraph: {
      type: 'website',
      siteName: siteConfig.name,
      title: fullTitle,
      description,
      url,
      locale: ogLocales[locale],
      alternateLocale: locales.filter((l) => l !== locale).map((l) => ogLocales[l]),
      images,
    },
    twitter: {
      card: 'summary_large_image',
      title: fullTitle,
      description,
      images,
    },
  }
}
